import { createClient } from '@supabase/supabase-js'
import { Capacitor } from '@capacitor/core'
import { getImpersonatedRole, setImpersonatedRole } from './impersonation'
import { getCurrentApp, type AppSlug } from './currentApp'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables. Check your .env file.')
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    // PKCE is required for mobile OAuth and magic-link flows inside a
    // Capacitor WebView, where the implicit flow cannot safely receive tokens.
    flowType: 'pkce',
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
})

// ── Auth redirect URLs ──────────────────────────────────────────────────────
//
// Every auth email and OAuth round-trip has to come back to the app the user
// actually started from: someone signing in to BattleCards should never be
// handed a battleplan.app link. On web that falls out of using the live origin.
// On native there's no meaningful origin, so each app's custom URL scheme is
// registered here.

/**
 * Custom URL scheme per app, used to bring a native user back into their app
 * after an auth redirect. Each entry must match that app's `appId` in its
 * capacitor.config.ts and the intent filter in its AndroidManifest.xml.
 *
 * Only BattleCards currently ships a native project; the others are listed so
 * that adding one doesn't silently deep-link users into the wrong app, which is
 * what a single hardcoded scheme here used to do.
 */
const NATIVE_SCHEMES: Record<AppSlug, string> = {
  battlecards: 'com.bamington.battlecards',
  battleplan: 'com.bamington.battleplan',
  battlebox: 'com.bamington.battlebench',
  battlepack: 'com.bamington.battlepack',
}

/**
 * Absolute URL for Supabase to return the user to after an auth flow, always
 * on the app that's currently running.
 *
 * Call it at the point of use rather than caching the result: the app slug is
 * registered by main.tsx at startup, which happens after this module loads.
 */
export function authRedirectTo(path: string = '/auth/callback'): string {
  if (Capacitor.isNativePlatform()) {
    const slug = getCurrentApp()
    const scheme = slug ? NATIVE_SCHEMES[slug] : undefined
    if (!scheme) {
      // Better to fail loudly in a native build than to send the user to
      // another app's deep link, which is unrecoverable from their side.
      throw new Error(
        `No native URL scheme registered for app "${slug ?? 'unknown'}". ` +
        'Call setCurrentApp() in main.tsx and add the app to NATIVE_SCHEMES.'
      )
    }
    return `${scheme}:/${path}`
  }
  return `${window.location.origin}${path}`
}

// ── Cross-app session hand-off ──────────────────────────────────────────────
//
// The Battleplans apps live on different origins (battlecards.app vs
// battleplan.app, and distinct *.vercel.app subdomains while testing), so they
// can't share localStorage or cookies. To keep the user logged in when they
// switch apps, the source app puts a single-use token in the destination URL's
// hash and the destination redeems it for a session of its own.
//
// The token deliberately is NOT the user's refresh token. Supabase rotates
// refresh tokens, so two origins holding the same one will revoke each other in
// turn and sign the user out at random — the bug this hand-off used to cause.
// The auth-handoff Edge Function mints a fresh single-use token instead, so
// each app ends up with an independent session. The hash is never sent to a
// server, and we scrub it from the URL as soon as it's consumed.

const HANDOFF_HASH_KEY = 'bp_handoff'
// Superseded by bp_handoff. Still read (not written) so a link generated by an
// older bundle, or by a tab left open across a deploy, still signs the user in.
const LEGACY_SESSION_HASH_KEY = 'bp_session'
// An admin's "view as" role travels with the session so the lens survives a
// switch between apps — the gate being per-app is the point of testing it.
const ROLE_HASH_KEY = 'bp_role'

/**
 * Append a single-use sign-in token to a cross-app URL so the destination can
 * start its own session. Returns the href unchanged when there's no session, or
 * on native, where each platform is a single app and storage isn't split across
 * origins.
 */
export async function appendSessionToUrl(href: string): Promise<string> {
  if (Capacitor.isNativePlatform()) return href
  const { data: { session } } = await supabase.auth.getSession()
  if (!session) return href

  const sep = href.includes('#') ? '&' : '#'
  const role = getImpersonatedRole()
  const roleParam = role ? `&${ROLE_HASH_KEY}=${role}` : ''

  const { data, error } = await supabase.functions.invoke<{ token_hash: string }>('auth-handoff')
  if (error || !data?.token_hash) {
    // The switcher still has to work if the function is down or not yet
    // deployed, so fall back to the old token copy. It can resurface the
    // rotation clash above, which is why it's the fallback and not the path.
    console.warn('Cross-app hand-off token unavailable, falling back to session copy', error)
    const payload = encodeURIComponent(JSON.stringify({
      access_token: session.access_token,
      refresh_token: session.refresh_token,
    }))
    return `${href}${sep}${LEGACY_SESSION_HASH_KEY}=${payload}${roleParam}`
  }

  return `${href}${sep}${HANDOFF_HASH_KEY}=${encodeURIComponent(data.token_hash)}${roleParam}`
}

/**
 * Redeem a session handed off via the URL hash, then scrub the token from the
 * URL and browser history. Call once, before the app reads the session. No-op
 * when there's no hand-off token present.
 */
export async function consumeSessionFromUrl(): Promise<void> {
  if (typeof window === 'undefined' || !window.location.hash) return
  const params = new URLSearchParams(window.location.hash.replace(/^#/, ''))
  const handoff = params.get(HANDOFF_HASH_KEY)
  const legacy = params.get(LEGACY_SESSION_HASH_KEY)
  const role = params.get(ROLE_HASH_KEY)
  if (!handoff && !legacy && !role) return

  // Carry over an admin's "view as" lens. Safe to apply before knowing whether
  // the arriving user is an admin: my_platform_apps() ignores the pretend role
  // for anyone who isn't, and it can only ever narrow what they see.
  if (role === 'user' || role === 'beta_tester') setImpersonatedRole(role)

  if (handoff) {
    // Redeeming the token mints a session that belongs to this origin alone.
    const { error } = await supabase.auth.verifyOtp({
      token_hash: decodeURIComponent(handoff),
      type: 'magiclink',
    })
    if (error) {
      // Expired or already redeemed (a refresh re-uses the same URL). Fall
      // through to scrubbing; the route guard will send them to /login.
      console.warn('Cross-app hand-off token could not be redeemed', error)
    }
  } else if (legacy) {
    try {
      const { access_token, refresh_token } = JSON.parse(decodeURIComponent(legacy))
      if (access_token && refresh_token) {
        await supabase.auth.setSession({ access_token, refresh_token })
      }
    } catch {
      // Malformed hand-off — ignore and fall through to scrubbing the URL.
    }
  }

  // Remove the token from the URL + history so it can't leak or be re-used.
  params.delete(HANDOFF_HASH_KEY)
  params.delete(LEGACY_SESSION_HASH_KEY)
  params.delete(ROLE_HASH_KEY)
  const rest = params.toString()
  const clean = window.location.pathname + window.location.search + (rest ? `#${rest}` : '')
  window.history.replaceState(null, '', clean)
}
