-- migration_battles.sql
--
-- Battle history from the previous BattlePlan app. This is BattleBox data —
-- nothing in BattleCards or BattlePlan reads it yet; the table sits dormant
-- until BattleBox is built, the same way the battlebox-tagged updates do.
--
-- Run once in the Supabase SQL editor for the shared project, BEFORE the
-- accompanying data import.

create table if not exists public.battles (
  -- Old integer ids are preserved. `by default as identity` lets us insert them
  -- explicitly now and still auto-generate ids for new battles later.
  id            bigint      generated by default as identity primary key,

  user_id       uuid        not null references auth.users (id) on delete cascade,
  game_id       uuid                 references public.games (id) on delete restrict,

  date_played   date        not null,
  opp_name      text        not null,

  -- Plain columns, deliberately without foreign keys: the `opponents` and
  -- `campaigns` tables haven't been migrated yet. Add the constraints then.
  opponent_id   bigint,
  campaign_id   uuid,

  -- Result from the battle owner's perspective. `winner` names the opponent who
  -- won, so a multi-opponent battle can record which one it was. It's only
  -- meaningful on a loss.
  result        text        not null check (result in ('won', 'lost', 'drew')),
  winner        text,

  -- Venue as text (a snapshot, so editing a location never rewrites history),
  -- plus a nullable link for the venues that do exist in our locations table.
  -- Most of these venues aren't ours, so location_id is usually null.
  location_name text,
  location_id   uuid                 references public.locations (id) on delete set null,

  battle_notes  text,
  created_at    timestamptz not null default now(),

  constraint battles_winner_only_on_loss check (winner is null or result = 'lost')
);

-- ── Indexes ──────────────────────────────────────────────────────────────────

create index if not exists battles_user_id_idx     on public.battles (user_id);
create index if not exists battles_date_played_idx on public.battles (date_played desc);
create index if not exists battles_campaign_id_idx on public.battles (campaign_id);
create index if not exists battles_game_id_idx     on public.battles (game_id);

-- ── Row Level Security ───────────────────────────────────────────────────────
-- A battle is personal: only its owner may read or write it.

alter table public.battles enable row level security;

drop policy if exists "battles_select_own" on public.battles;
create policy "battles_select_own" on public.battles
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "battles_insert_own" on public.battles;
create policy "battles_insert_own" on public.battles
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "battles_update_own" on public.battles;
create policy "battles_update_own" on public.battles
  for update to authenticated
  using      (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "battles_delete_own" on public.battles;
create policy "battles_delete_own" on public.battles
  for delete to authenticated using (user_id = auth.uid());
